#include <TROOT.h>
#include <TFile.h>
#include <TSystem.h>
#include <TString.h>
#include "TLorentzVector.h"

#include "finalPlot.C"

void makeAllPlots(TString nsel, int applyScaling, int year){
  TString legendBSM="";
  int isNeverBlinded=0;
  int isBlinded=0;
  TString fidAnaName="";
  TString mlfitResult="";
  TString channelName="XXX"; 
  double SF_DY=1.0;
  if(nsel == "z"){
    finalPlot(0,1,"m_{ll}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_0.root",year),"dy_zsel_massmm",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{ll}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_1.root",year),"dy_zsel_massem",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{ll}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_2.root",year),"dy_zsel_massee",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{ll}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_3.root",year),"dy_zsel_ptllmm",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{ll}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_4.root",year),"dy_zsel_ptllem",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{ll}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_5.root",year),"dy_zsel_ptllee",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#Delta R_{ll}","",Form("anaZ/fillhisto_zAnalysis1001_%d_6.root",year),"dy_zsel_drllmm",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#Delta R_{ll}","",Form("anaZ/fillhisto_zAnalysis1001_%d_7.root",year),"dy_zsel_drllem",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#Delta R_{ll}","",Form("anaZ/fillhisto_zAnalysis1001_%d_8.root",year),"dy_zsel_drllee",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#Delta #phi_{ll}","",Form("anaZ/fillhisto_zAnalysis1001_%d_9.root",year),"dy_zsel_dphillmm",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#Delta #phi_{ll}","",Form("anaZ/fillhisto_zAnalysis1001_%d_10.root",year),"dy_zsel_dphillem",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#Delta #phi_{ll}","",Form("anaZ/fillhisto_zAnalysis1001_%d_11.root",year),"dy_zsel_dphillee",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{l1}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_12.root",year),"dy_zsel_ptl1mm",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{l1}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_13.root",year),"dy_zsel_ptl1em",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{l1}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_14.root",year),"dy_zsel_ptl1ee",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{l2}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_15.root",year),"dy_zsel_ptl2mm",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{l2}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_16.root",year),"dy_zsel_ptl2em",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{l2}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_17.root",year),"dy_zsel_ptl2ee",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#eta_{T}^{l1}","",Form("anaZ/fillhisto_zAnalysis1001_%d_18.root",year),"dy_zsel_etal1mm",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#eta_{T}^{l1}","",Form("anaZ/fillhisto_zAnalysis1001_%d_19.root",year),"dy_zsel_etal1em",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#eta_{T}^{l1}","",Form("anaZ/fillhisto_zAnalysis1001_%d_20.root",year),"dy_zsel_etal1ee",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#eta_{T}^{l2}","",Form("anaZ/fillhisto_zAnalysis1001_%d_21.root",year),"dy_zsel_etal2mm",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#eta_{T}^{l2}","",Form("anaZ/fillhisto_zAnalysis1001_%d_22.root",year),"dy_zsel_etal2em",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#eta_{T}^{l2}","",Form("anaZ/fillhisto_zAnalysis1001_%d_23.root",year),"dy_zsel_etal2ee",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"N_{j}","",Form("anaZ/fillhisto_zAnalysis1001_%d_24.root",year),"dy_zsel_njetsmm",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"N_{j}","",Form("anaZ/fillhisto_zAnalysis1001_%d_25.root",year),"dy_zsel_njetsem",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"N_{j}","",Form("anaZ/fillhisto_zAnalysis1001_%d_26.root",year),"dy_zsel_njetsee",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"N_{bj}","",Form("anaZ/fillhisto_zAnalysis1001_%d_27.root",year),"dy_zsel_nbjetsmm",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"N_{bj}","",Form("anaZ/fillhisto_zAnalysis1001_%d_28.root",year),"dy_zsel_nbjetsem",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"N_{bj}","",Form("anaZ/fillhisto_zAnalysis1001_%d_29.root",year),"dy_zsel_nbjetsee",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"NPV","",Form("anaZ/fillhisto_zAnalysis1001_%d_30.root",year),"dy_zsel_npvmm",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"NPV","",Form("anaZ/fillhisto_zAnalysis1001_%d_31.root",year),"dy_zsel_npvem",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"NPV","",Form("anaZ/fillhisto_zAnalysis1001_%d_32.root",year),"dy_zsel_npvee",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{jj}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_33.root",year),"dy_zsel_mjjmm",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{jj}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_34.root",year),"dy_zsel_mjjem",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{jj}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_35.root",year),"dy_zsel_mjjee",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{jj}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_36.root",year),"dy_zsel_ptjjmm",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{jj}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_37.root",year),"dy_zsel_ptjjem",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{jj}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_38.root",year),"dy_zsel_ptjjee",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#Delta #eta_{jj}","",Form("anaZ/fillhisto_zAnalysis1001_%d_39.root",year),"dy_zsel_detajjmm",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#Delta #eta_{jj}","",Form("anaZ/fillhisto_zAnalysis1001_%d_40.root",year),"dy_zsel_detajjem",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#Delta #eta_{jj}","",Form("anaZ/fillhisto_zAnalysis1001_%d_41.root",year),"dy_zsel_detajjee",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#Delta #phi_{jj}","",Form("anaZ/fillhisto_zAnalysis1001_%d_42.root",year),"dy_zsel_dphijjmm",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#Delta #phi_{jj}","",Form("anaZ/fillhisto_zAnalysis1001_%d_43.root",year),"dy_zsel_dphijjem",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#Delta #phi_{jj}","",Form("anaZ/fillhisto_zAnalysis1001_%d_44.root",year),"dy_zsel_dphijjee",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"Btag","",Form("anaZ/fillhisto_zAnalysis1001_%d_45.root",year),"dy_zsel_btagDeepBmm",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"Btag","",Form("anaZ/fillhisto_zAnalysis1001_%d_46.root",year),"dy_zsel_btagDeepBem",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"Btag","",Form("anaZ/fillhisto_zAnalysis1001_%d_47.root",year),"dy_zsel_btagDeepBee",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{j}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_48.root",year),"dy_zsel_ptjmm",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{j}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_49.root",year),"dy_zsel_ptjem",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{j}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_50.root",year),"dy_zsel_ptjee",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#eta_{T}^{j}","",Form("anaZ/fillhisto_zAnalysis1001_%d_51.root",year),"dy_zsel_etajmm",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#eta_{T}^{j}","",Form("anaZ/fillhisto_zAnalysis1001_%d_52.root",year),"dy_zsel_etajem",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#eta_{T}^{j}","",Form("anaZ/fillhisto_zAnalysis1001_%d_53.root",year),"dy_zsel_etajee",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"Calo p_{T}^{miss}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_54.root",year),"dy_zsel_calometmm",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"Calo p_{T}^{miss}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_55.root",year),"dy_zsel_calometem",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"Calo p_{T}^{miss}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_56.root",year),"dy_zsel_calometee",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"CHS p_{T}^{miss}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_57.root",year),"dy_zsel_chsmetmm",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"CHS p_{T}^{miss}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_58.root",year),"dy_zsel_chsmetem",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"CHS p_{T}^{miss}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_59.root",year),"dy_zsel_chsmetee",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{miss}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_154.root",year),"dy_zsel_metmm",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{miss}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_155.root",year),"dy_zsel_metem",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{miss}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_156.root",year),"dy_zsel_metee",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"PUPPI p_{T}^{miss}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_157.root",year),"dy_zsel_puppimetmm",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"PUPPI p_{T}^{miss}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_158.root",year),"dy_zsel_puppimetem",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"PUPPI p_{T}^{miss}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_159.root",year),"dy_zsel_puppimetee",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"TRK p_{T}^{miss}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_176.root",year),"dy_zsel_trkmetmm",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"TRK p_{T}^{miss}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_177.root",year),"dy_zsel_trkmetem",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"TRK p_{T}^{miss}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_178.root",year),"dy_zsel_trkmetee",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{ll}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_179.root",year),"dy_zsel_massmm_trig0",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{ll}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_180.root",year),"dy_zsel_massem_trig0",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{ll}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_181.root",year),"dy_zsel_massee_trig0",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{ll}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_182.root",year),"dy_zsel_massmm_trig1",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{ll}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_183.root",year),"dy_zsel_massem_trig1",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{ll}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_184.root",year),"dy_zsel_massee_trig1",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{ll}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_185.root",year),"dy_zsel_massmm_trig2",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{ll}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_186.root",year),"dy_zsel_massem_trig2",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{ll}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_187.root",year),"dy_zsel_massee_trig2",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{ll}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_188.root",year),"dy_zsel_massmm_trig3",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{ll}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_189.root",year),"dy_zsel_massem_trig3",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{ll}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_190.root",year),"dy_zsel_massee_trig3",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{ll}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_191.root",year),"dy_zsel_massmm_trig4",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{ll}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_192.root",year),"dy_zsel_massem_trig4",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{ll}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_193.root",year),"dy_zsel_massee_trig4",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{ll}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_194.root",year),"dy_zsel_massmm_trig5",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{ll}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_195.root",year),"dy_zsel_massem_trig5",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{ll}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_196.root",year),"dy_zsel_massee_trig5",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{ll}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_197.root",year),"dy_zsel_massmm_trig6",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{ll}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_198.root",year),"dy_zsel_massem_trig6",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{ll}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_199.root",year),"dy_zsel_massee_trig6",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{ll}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_200.root",year),"dy_zsel_massmm_trig7",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{ll}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_201.root",year),"dy_zsel_massem_trig7",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{ll}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_202.root",year),"dy_zsel_massee_trig7",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{ll}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_203.root",year),"dy_zsel_massmm_trig8",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{ll}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_204.root",year),"dy_zsel_massem_trig8",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{ll}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_205.root",year),"dy_zsel_massee_trig8",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{l}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_206.root",year),"dy_zme_pttag",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{l}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_207.root",year),"dy_zem_pttag",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{l}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_208.root",year),"dy_zme_pttag_trig",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{l}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_209.root",year),"dy_zem_pttag_trig",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{l}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_210.root",year),"dy_zme_ptprobe",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{l}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_211.root",year),"dy_zem_ptprobe",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{l}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_212.root",year),"dy_zme_ptprobe_trigem",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{l}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_213.root",year),"dy_zem_ptprobe_trigem",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{l}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_214.root",year),"dy_zme_ptprobe_trigse",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{l}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_215.root",year),"dy_zem_ptprobe_trigsm",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());

    finalPlot(0,1,"MVA","",Form("anaZ/fillhisto_zAnalysis1001_%d_160.root",year),"dy_zsel_tthmvam",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"MVA","",Form("anaZ/fillhisto_zAnalysis1001_%d_161.root",year),"dy_zsel_tthmvae",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());

    finalPlot(0,1,"m_{llg}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_170.root",year),"dy_mmmg",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{llg}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_171.root",year),"dy_memg",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{llg}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_172.root",year),"dy_meeg",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{#gamma}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_173.root",year),"dy_mmg_ptg",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{#gamma}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_174.root",year),"dy_emg_ptg",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{#gamma}","GeV",Form("anaZ/fillhisto_zAnalysis1001_%d_175.root",year),"dy_eeg_ptg",0,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
  }
  else if(nsel == "fake"){
    legendBSM="";
    isNeverBlinded=0;
    isBlinded=0;
    fidAnaName="";
    mlfitResult="";
    channelName="XXX"; 

    SF_DY=0.9;
    finalPlot(0,1,"X","GeV",Form("anaZ/fillhisto_fakeAnalysis1001_%d_0.root",year),"fakemsel_mt", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"X","GeV",Form("anaZ/fillhisto_fakeAnalysis1001_%d_2.root",year),"fakemsel_dphilmet", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"X","GeV",Form("anaZ/fillhisto_fakeAnalysis1001_%d_4.root",year),"fakemsel_met", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"X","GeV",Form("anaZ/fillhisto_fakeAnalysis1001_%d_6.root",year),"fakemsel_mt_fix", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"X","GeV",Form("anaZ/fillhisto_fakeAnalysis1001_%d_8.root",year),"fakemsel_ptloose", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"X","GeV",Form("anaZ/fillhisto_fakeAnalysis1001_%d_10.root",year),"fakemsel_etaloose", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"X","GeV",Form("anaZ/fillhisto_fakeAnalysis1001_%d_12.root",year),"fakemsel_pttight", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"X","GeV",Form("anaZ/fillhisto_fakeAnalysis1001_%d_14.root",year),"fakemsel_etatight", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"X","GeV",Form("anaZ/fillhisto_fakeAnalysis1001_%d_16.root",year),"fakemsel_sel0_mt_fix", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"X","GeV",Form("anaZ/fillhisto_fakeAnalysis1001_%d_18.root",year),"fakemsel_sel1_mt_fix", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"X","GeV",Form("anaZ/fillhisto_fakeAnalysis1001_%d_20.root",year),"fakemsel_sel2_mt_fix", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"X","GeV",Form("anaZ/fillhisto_fakeAnalysis1001_%d_22.root",year),"fakemsel_sel3_mt_fix", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"X","GeV",Form("anaZ/fillhisto_fakeAnalysis1001_%d_24.root",year),"fakemsel_sel4_mt_fix", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"X","GeV",Form("anaZ/fillhisto_fakeAnalysis1001_%d_26.root",year),"fakemsel_sel5_mt_fix", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"X","GeV",Form("anaZ/fillhisto_fakeAnalysis1001_%d_28.root",year),"fakemsel_sel0_mt", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"X","GeV",Form("anaZ/fillhisto_fakeAnalysis1001_%d_30.root",year),"fakemsel_sel1_mt", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"X","GeV",Form("anaZ/fillhisto_fakeAnalysis1001_%d_32.root",year),"fakemsel_sel2_mt", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"X","GeV",Form("anaZ/fillhisto_fakeAnalysis1001_%d_34.root",year),"fakemsel_sel3_mt", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"X","GeV",Form("anaZ/fillhisto_fakeAnalysis1001_%d_36.root",year),"fakemsel_sel4_mt", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"X","GeV",Form("anaZ/fillhisto_fakeAnalysis1001_%d_38.root",year),"fakemsel_sel5_mt", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"X","GeV",Form("anaZ/fillhisto_fakeAnalysis1001_%d_40.root",year),"fakemsel_ptl", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"X","GeV",Form("anaZ/fillhisto_fakeAnalysis1001_%d_42.root",year),"fakemsel_tthmva", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());

    SF_DY=0.8;
    finalPlot(0,1,"X","GeV",Form("anaZ/fillhisto_fakeAnalysis1001_%d_1.root",year),"fakeesel_mt", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"X","GeV",Form("anaZ/fillhisto_fakeAnalysis1001_%d_3.root",year),"fakeesel_dphilmet", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"X","GeV",Form("anaZ/fillhisto_fakeAnalysis1001_%d_5.root",year),"fakeesel_met", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"X","GeV",Form("anaZ/fillhisto_fakeAnalysis1001_%d_7.root",year),"fakeesel_mt_fix", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"X","GeV",Form("anaZ/fillhisto_fakeAnalysis1001_%d_9.root",year),"fakeesel_ptloose", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"X","GeV",Form("anaZ/fillhisto_fakeAnalysis1001_%d_11.root",year),"fakeesel_etaloose", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"X","GeV",Form("anaZ/fillhisto_fakeAnalysis1001_%d_13.root",year),"fakeesel_pttight", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"X","GeV",Form("anaZ/fillhisto_fakeAnalysis1001_%d_15.root",year),"fakeesel_etatight", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"X","GeV",Form("anaZ/fillhisto_fakeAnalysis1001_%d_17.root",year),"fakeesel_sel0_mt_fix", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"X","GeV",Form("anaZ/fillhisto_fakeAnalysis1001_%d_19.root",year),"fakeesel_sel1_mt_fix", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"X","GeV",Form("anaZ/fillhisto_fakeAnalysis1001_%d_21.root",year),"fakeesel_sel2_mt_fix", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"X","GeV",Form("anaZ/fillhisto_fakeAnalysis1001_%d_23.root",year),"fakeesel_sel3_mt_fix", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"X","GeV",Form("anaZ/fillhisto_fakeAnalysis1001_%d_25.root",year),"fakeesel_sel4_mt_fix", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"X","GeV",Form("anaZ/fillhisto_fakeAnalysis1001_%d_27.root",year),"fakeesel_sel5_mt_fix", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"X","GeV",Form("anaZ/fillhisto_fakeAnalysis1001_%d_29.root",year),"fakeesel_sel0_mt", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"X","GeV",Form("anaZ/fillhisto_fakeAnalysis1001_%d_31.root",year),"fakeesel_sel1_mt", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"X","GeV",Form("anaZ/fillhisto_fakeAnalysis1001_%d_33.root",year),"fakeesel_sel2_mt", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"X","GeV",Form("anaZ/fillhisto_fakeAnalysis1001_%d_35.root",year),"fakeesel_sel3_mt", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"X","GeV",Form("anaZ/fillhisto_fakeAnalysis1001_%d_37.root",year),"fakeesel_sel4_mt", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"X","GeV",Form("anaZ/fillhisto_fakeAnalysis1001_%d_39.root",year),"fakeesel_sel5_mt", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"X","GeV",Form("anaZ/fillhisto_fakeAnalysis1001_%d_41.root",year),"fakeesel_ptl", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"X","GeV",Form("anaZ/fillhisto_fakeAnalysis1001_%d_43.root",year),"fakeesel_tthmva", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
  }
  else if(nsel == "wz"){
    legendBSM="";
    isNeverBlinded=0;
    isBlinded=0;
    fidAnaName="";
    mlfitResult="";
    channelName="XXX"; 
    SF_DY=1;
    finalPlot(0,1,"Min(m_{ll})","GeV",Form("anaZ/fillhisto_wzAnalysis1001_%d_0.root",year),"wzsel_mllmin", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"|m_{ll}-m_{Z}|","GeV",Form("anaZ/fillhisto_wzAnalysis1001_%d_1.root",year),"wzsel_mllz", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{3l}","GeV",Form("anaZ/fillhisto_wzAnalysis1001_%d_2.root",year),"wzsel_m3l", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{l-W}","GeV",Form("anaZ/fillhisto_wzAnalysis1001_%d_3.root",year),"wzsel_ptlw", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"N_{b jets}","",Form("anaZ/fillhisto_wzAnalysis1001_%d_4.root",year),"wzsel_nbtagjet", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"Leading p_{T}^{l-Z}","GeV",Form("anaZ/fillhisto_wzAnalysis1001_%d_5.root",year),"wzsel_ptlz1", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"Leading p_{T}^{l-Z}","GeV",Form("anaZ/fillhisto_wzAnalysis1001_%d_6.root",year),"wzbsel_ptlz1", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"Trailing p_{T}^{l-Z}","GeV",Form("anaZ/fillhisto_wzAnalysis1001_%d_7.root",year),"wzsel_ptlz2", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"Trailing p_{T}^{l-Z}","GeV",Form("anaZ/fillhisto_wzAnalysis1001_%d_8.root",year),"wzbsel_ptlz2", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{T}^{W}","GeV",Form("anaZ/fillhisto_wzAnalysis1001_%d_9.root",year),"wzsel_mtw", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{T}^{W}","GeV",Form("anaZ/fillhisto_wzAnalysis1001_%d_10.root",year),"wzbsel_mtw", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"Lepton type","",Form("anaZ/fillhisto_wzAnalysis1001_%d_11.root",year),"wzsel_ltype", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"Lepton type","",Form("anaZ/fillhisto_wzAnalysis1001_%d_12.root",year),"wzbsel_ltype", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"N_{jets}","",Form("anaZ/fillhisto_wzAnalysis1001_%d_13.root",year),"wzsel_njets", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"N_{jets}","",Form("anaZ/fillhisto_wzAnalysis1001_%d_14.root",year),"wzbsel_njets", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{miss}","GeV",Form("anaZ/fillhisto_wzAnalysis1001_%d_15.root",year),"wzsel_ptmiss", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{miss}","GeV",Form("anaZ/fillhisto_wzAnalysis1001_%d_16.root",year),"wzbsel_ptmiss", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"N_{jets}","",Form("anaZ/fillhisto_wzAnalysis1001_%d_17.root",year),"wzjjsel_njets", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"N_{jets}","",Form("anaZ/fillhisto_wzAnalysis1001_%d_18.root",year),"wzbjjsel_njets", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{jj}","GeV",Form("anaZ/fillhisto_wzAnalysis1001_%d_19.root",year),"wzjjsel_mjj", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{jj}","GeV",Form("anaZ/fillhisto_wzAnalysis1001_%d_20.root",year),"wzbjjsel_mjj", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#Delta#eta_{jj}","",Form("anaZ/fillhisto_wzAnalysis1001_%d_21.root",year),"wzjjsel_detajj", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#Delta#eta_{jj}","",Form("anaZ/fillhisto_wzAnalysis1001_%d_22.root",year),"wzbjjsel_detajj", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#Delta#phi_{jj}","",Form("anaZ/fillhisto_wzAnalysis1001_%d_23.root",year),"wzjjsel_dphijj", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#Delta#phi_{jj}","",Form("anaZ/fillhisto_wzAnalysis1001_%d_24.root",year),"wzbjjsel_dphijj", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"BDT","",Form("anaZ/fillhisto_wzAnalysis1001_%d_25.root",year),"wzjjsel_bdt_vbfincl", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"BDT","",Form("anaZ/fillhisto_wzAnalysis1001_%d_26.root",year),"wzbjjsel_bdt_vbfincl", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"N_{jets}","",Form("anaZ/fillhisto_wzAnalysis1001_%d_27.root",year),"wzvbssel_njets", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"N_{jets}","",Form("anaZ/fillhisto_wzAnalysis1001_%d_28.root",year),"wzbvbssel_njets", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{jj}","GeV",Form("anaZ/fillhisto_wzAnalysis1001_%d_29.root",year),"wzvbssel_mjj", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{jj}","GeV",Form("anaZ/fillhisto_wzAnalysis1001_%d_30.root",year),"wzbvbssel_mjj", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#Delta#eta_{jj}","",Form("anaZ/fillhisto_wzAnalysis1001_%d_31.root",year),"wzvbssel_detajj", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#Delta#eta_{jj}","",Form("anaZ/fillhisto_wzAnalysis1001_%d_32.root",year),"wzbvbssel_detajj", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#Delta#phi_{jj}","",Form("anaZ/fillhisto_wzAnalysis1001_%d_33.root",year),"wzvbssel_dphijj", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#Delta#phi_{jj}","",Form("anaZ/fillhisto_wzAnalysis1001_%d_34.root",year),"wzbvbssel_dphijj", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"BDT","",Form("anaZ/fillhisto_wzAnalysis1001_%d_35.root",year),"wzvbssel_bdt_vbfincl", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"BDT","",Form("anaZ/fillhisto_wzAnalysis1001_%d_36.root",year),"wzbvbssel_bdt_vbfincl", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{3l}","GeV",Form("anaZ/fillhisto_wzAnalysis1001_%d_37.root",year),"llgsel_m3l", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"Lepton type","",Form("anaZ/fillhisto_wzAnalysis1001_%d_38.root",year),"llgsel_ltype", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{#gamma}","GeV",Form("anaZ/fillhisto_wzAnalysis1001_%d_39.root",year),"llgsel_ptle", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{#gamma}","GeV",Form("anaZ/fillhisto_wzAnalysis1001_%d_40.root",year),"llgsel_ptlm", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"N_{b jets}","",Form("anaZ/fillhisto_wzAnalysis1001_%d_51.root",year),"whsel_nbtagjet", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"N_{jets}","",Form("anaZ/fillhisto_wzAnalysis1001_%d_52.root",year),"whsel_njets", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"Lepton type","",Form("anaZ/fillhisto_wzAnalysis1001_%d_53.root",year),"whsel_ltype", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"Min(m_{ll})","GeV",Form("anaZ/fillhisto_wzAnalysis1001_%d_54.root",year),"whsel_mllmin", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#Delta R_{ll}","",Form("anaZ/fillhisto_wzAnalysis1001_%d_55.root",year),"whsel_drllmin", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{l3}","GeV",Form("anaZ/fillhisto_wzAnalysis1001_%d_56.root",year),"whsel_ptl3", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"N_{jets}","",Form("anaZ/fillhisto_wzAnalysis1001_%d_57.root",year),"wzsel_mmm_njets", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"N_{jets}","",Form("anaZ/fillhisto_wzAnalysis1001_%d_58.root",year),"wzsel_emm_njets", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"N_{jets}","",Form("anaZ/fillhisto_wzAnalysis1001_%d_59.root",year),"wzsel_mee_njets", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"N_{jets}","",Form("anaZ/fillhisto_wzAnalysis1001_%d_60.root",year),"wzsel_eee_njets", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{l}","GeV",Form("anaZ/fillhisto_wzAnalysis1001_%d_61.root",year),"wzsel_pttag_trigger0", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{l}","GeV",Form("anaZ/fillhisto_wzAnalysis1001_%d_62.root",year),"wzsel_pttag_trigger1", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{l}","GeV",Form("anaZ/fillhisto_wzAnalysis1001_%d_63.root",year),"wzsel_pttag_trigger2", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{l}","GeV",Form("anaZ/fillhisto_wzAnalysis1001_%d_64.root",year),"wzsel_pttag_trigger3", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{l}","GeV",Form("anaZ/fillhisto_wzAnalysis1001_%d_65.root",year),"wzsel_ptl_trigger0", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{l}","GeV",Form("anaZ/fillhisto_wzAnalysis1001_%d_66.root",year),"wzsel_ptl_trigger1", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{l}","GeV",Form("anaZ/fillhisto_wzAnalysis1001_%d_67.root",year),"wzsel_ptl_trigger2", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{l}","GeV",Form("anaZ/fillhisto_wzAnalysis1001_%d_68.root",year),"wzsel_ptl_trigger3", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{l}","GeV",Form("anaZ/fillhisto_wzAnalysis1001_%d_69.root",year),"wzsel_ptl_trigger4", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{l}","GeV",Form("anaZ/fillhisto_wzAnalysis1001_%d_70.root",year),"wzsel_ptl_trigger5", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{l}","GeV",Form("anaZ/fillhisto_wzAnalysis1001_%d_71.root",year),"wzsel_ptl_trigger6", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{l}","GeV",Form("anaZ/fillhisto_wzAnalysis1001_%d_72.root",year),"wzsel_ptl_trigger7", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
  }
  else if(nsel == "zz"){
    legendBSM="";
    isNeverBlinded=0;
    isBlinded=0;
    fidAnaName="";
    mlfitResult="";
    channelName="XXX"; 
    SF_DY=1;
    finalPlot(0,1,"Min(m_{ll})","GeV",Form("anaZ/fillhisto_zzAnalysis1001_%d_0.root",year),"zzsel_mllmin", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"|m_{ll}-m_{Z1}|","GeV",Form("anaZ/fillhisto_zzAnalysis1001_%d_1.root",year),"zzsel_mllz1", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"|m_{ll}-m_{Z2}|","GeV",Form("anaZ/fillhisto_zzAnalysis1001_%d_2.root",year),"zzsel_mllz2", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"Leading p_{T}^{l-Z1}","GeV",Form("anaZ/fillhisto_zzAnalysis1001_%d_3.root",year),"zzsel_ptlz11", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"Trailing p_{T}^{l-Z1}","GeV",Form("anaZ/fillhisto_zzAnalysis1001_%d_4.root",year),"zzsel_ptlz12", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"Leading p_{T}^{l-Z1}","GeV",Form("anaZ/fillhisto_zzAnalysis1001_%d_5.root",year),"zzsel_ptlz21", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"Trailing p_{T}^{l-Z1}","GeV",Form("anaZ/fillhisto_zzAnalysis1001_%d_6.root",year),"zzsel_ptlz22", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{4l}","GeV",Form("anaZ/fillhisto_zzAnalysis1001_%d_7.root",year),"zzsel_m4l", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"Lepton type","",Form("anaZ/fillhisto_zzAnalysis1001_%d_8.root",year),"zzsel_ltype", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"N_{jets}","",Form("anaZ/fillhisto_zzAnalysis1001_%d_9.root",year),"zzsel_njets", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{miss}","GeV",Form("anaZ/fillhisto_zzAnalysis1001_%d_10.root",year),"zzsel_ptmiss", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"N_{jets}","",Form("anaZ/fillhisto_zzAnalysis1001_%d_11.root",year),"zzjjsel_njets", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{jj}","GeV",Form("anaZ/fillhisto_zzAnalysis1001_%d_12.root",year),"zzjjsel_mjj", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#Delta#eta_{jj}","",Form("anaZ/fillhisto_zzAnalysis1001_%d_13.root",year),"zzjjsel_detajj", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#Delta#phi_{jj}","",Form("anaZ/fillhisto_zzAnalysis1001_%d_14.root",year),"zzjjsel_dphijj", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"BDT","",Form("anaZ/fillhisto_zzAnalysis1001_%d_15.root",year),"zzjjsel_bdt_vbfincl", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"N_{jets}","",Form("anaZ/fillhisto_zzAnalysis1001_%d_16.root",year),"zzvbssel_njets", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{jj}","GeV",Form("anaZ/fillhisto_zzAnalysis1001_%d_17.root",year),"zzvbssel_mjj", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#Delta#eta_{jj}","",Form("anaZ/fillhisto_zzAnalysis1001_%d_18.root",year),"zzvbssel_detajj", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#Delta#phi_{jj}","",Form("anaZ/fillhisto_zzAnalysis1001_%d_19.root",year),"zzvbssel_dphijj", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"BDT","",Form("anaZ/fillhisto_zzAnalysis1001_%d_20.root",year),"zzvbssel_bdt_vbfincl", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"Lepton type","",Form("anaZ/fillhisto_zzAnalysis1001_%d_21.root",year),"zzsel_no4l_ltype", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{4l}","GeV",Form("anaZ/fillhisto_zzAnalysis1001_%d_22.root",year),"zzsel_no4l_m4l", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"N_{bjets}","",Form("anaZ/fillhisto_zzAnalysis1001_%d_23.root",year),"zzsel_no4l_nbjets", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"N_{bjets}","",Form("anaZ/fillhisto_zzAnalysis1001_%d_24.root",year),"zzsel_xy_nbjets", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{4l}","GeV",Form("anaZ/fillhisto_zzAnalysis1001_%d_25.root",year),"zzsel_xy_btagged_m4l", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"Lepton type","",Form("anaZ/fillhisto_zzAnalysis1001_%d_26.root",year),"zzsel_xy_nonbtagged_ltype", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{e#mu}","GeV",Form("anaZ/fillhisto_zzAnalysis1001_%d_27.root",year),"zzsel_xy_nonbtagged_mll", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{miss}","GeV",Form("anaZ/fillhisto_zzAnalysis1001_%d_28.root",year),"zzsel_xy_nonbtagged_met", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{4l}","GeV",Form("anaZ/fillhisto_zzAnalysis1001_%d_29.root",year),"zzsel_xy_nonbtagged_m4l", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{Z2}","GeV",Form("anaZ/fillhisto_zzAnalysis1001_%d_30.root",year),"zzsel_xy_nonbtagged_ptz2", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{T}^{Z2,met}","GeV",Form("anaZ/fillhisto_zzAnalysis1001_%d_31.root",year),"zzsel_xy_nonbtagged_mtxy", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
  }
  else if(nsel == "met"){
    legendBSM="";
    isNeverBlinded=0;
    isBlinded=0;
    fidAnaName="";
    mlfitResult="";
    channelName="XXX"; 
    SF_DY=1;
    finalPlot(0,1,"m_{tot}","GeV",Form("anaZ/fillhistoMETAna1001_%d_0.root",year),"metsel0_mtot", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{tot}","GeV",Form("anaZ/fillhistoMETAna1001_%d_1.root",year),"metsel1_mtot", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{tot}","GeV",Form("anaZ/fillhistoMETAna1001_%d_2.root",year),"metsel2_mtot", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{tot}","GeV",Form("anaZ/fillhistoMETAna1001_%d_3.root",year),"metsel3_mtot", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{tot}","GeV",Form("anaZ/fillhistoMETAna1001_%d_4.root",year),"metsel4_mtot", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{tot}","GeV",Form("anaZ/fillhistoMETAna1001_%d_5.root",year),"metsel5_mtot", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());

    finalPlot(0,1,"Min(m_{ll})","GeV",Form("anaZ/fillhistoMETAna1001_%d_6.root",year),"metsel0_mllmin", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"Min(m_{ll})","GeV",Form("anaZ/fillhistoMETAna1001_%d_7.root",year),"metsel1_mllmin", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"Min(m_{ll})","GeV",Form("anaZ/fillhistoMETAna1001_%d_8.root",year),"metsel2_mllmin", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"Min(m_{ll})","GeV",Form("anaZ/fillhistoMETAna1001_%d_9.root",year),"metsel3_mllmin", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"Min(m_{ll})","GeV",Form("anaZ/fillhistoMETAna1001_%d_10.root",year),"metsel4_mllmin", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"Min(m_{ll})","GeV",Form("anaZ/fillhistoMETAna1001_%d_11.root",year),"metsel5_mllmin", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
  }
  else if(nsel == "ssww"){
    legendBSM="";
    isNeverBlinded=0;
    isBlinded=0;
    fidAnaName="";
    mlfitResult="";
    channelName="XXX"; 
    SF_DY=1;
    finalPlot(0,1,"m_{ll}","GeV",Form("anaZ/fillhisto_sswwAnalysis1001_%d_0.root",year),"sswwpresel_mll", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"N_{bjets}","",Form("anaZ/fillhisto_sswwAnalysis1001_%d_1.root",year),"sswwpresel_nbjets", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{miss}","GeV",Form("anaZ/fillhisto_sswwAnalysis1001_%d_2.root",year),"sswwpresel_met", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{miss}","GeV",Form("anaZ/fillhisto_sswwAnalysis1001_%d_3.root",year),"sswwbpresel_met", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"Lepton type","",Form("anaZ/fillhisto_sswwAnalysis1001_%d_4.root",year),"sswwpresel_ltype", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"Lepton type","",Form("anaZ/fillhisto_sswwAnalysis1001_%d_5.root",year),"sswwbpresel_ltype", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"N_{jets}","",Form("anaZ/fillhisto_sswwAnalysis1001_%d_6.root",year),"sswwpresel_njets", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"N_{jets}","",Form("anaZ/fillhisto_sswwAnalysis1001_%d_7.root",year),"sswwbpresel_njets", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"Lepton type","",Form("anaZ/fillhisto_sswwAnalysis1001_%d_8.root",year),"sswwsel_ltype", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"Lepton type","",Form("anaZ/fillhisto_sswwAnalysis1001_%d_9.root",year),"sswwbsel_ltype", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"N_{jets}","",Form("anaZ/fillhisto_sswwAnalysis1001_%d_10.root",year),"sswwsel_njets", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"N_{jets}","",Form("anaZ/fillhisto_sswwAnalysis1001_%d_11.root",year),"sswwbsel_njets", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{jj}","GeV",Form("anaZ/fillhisto_sswwAnalysis1001_%d_12.root",year),"sswwsel_mjj", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{jj}","GeV",Form("anaZ/fillhisto_sswwAnalysis1001_%d_13.root",year),"sswwbsel_mjj", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#Delta#eta_{jj}","",Form("anaZ/fillhisto_sswwAnalysis1001_%d_14.root",year),"sswwsel_detajj", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#Delta#eta_{jj}","",Form("anaZ/fillhisto_sswwAnalysis1001_%d_15.root",year),"sswwbsel_detajj", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#Delta#phi_{jj}","",Form("anaZ/fillhisto_sswwAnalysis1001_%d_16.root",year),"sswwsel_dphijj", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#Delta#phi_{jj}","",Form("anaZ/fillhisto_sswwAnalysis1001_%d_17.root",year),"sswwbsel_dphijj", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"BDT","",Form("anaZ/fillhisto_sswwAnalysis1001_%d_18.root",year),"sswwjjsel_bdt_vbfincl", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"BDT","",Form("anaZ/fillhisto_sswwAnalysis1001_%d_19.root",year),"sswwbjjsel_bdt_vbfincl", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"Lepton type","",Form("anaZ/fillhisto_sswwAnalysis1001_%d_20.root",year),"sswwvbssel_ltype", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"Lepton type","",Form("anaZ/fillhisto_sswwAnalysis1001_%d_21.root",year),"sswwbvbssel_ltype", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"N_{jets}","",Form("anaZ/fillhisto_sswwAnalysis1001_%d_22.root",year),"sswwvbssel_njets", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"N_{jets}","",Form("anaZ/fillhisto_sswwAnalysis1001_%d_23.root",year),"sswwbvbssel_njets", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{jj}","GeV",Form("anaZ/fillhisto_sswwAnalysis1001_%d_24.root",year),"sswwvbssel_mjj", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{jj}","GeV",Form("anaZ/fillhisto_sswwAnalysis1001_%d_25.root",year),"sswwbvbssel_mjj", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#Delta#eta_{jj}","",Form("anaZ/fillhisto_sswwAnalysis1001_%d_26.root",year),"sswwvbssel_detajj", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#Delta#eta_{jj}","",Form("anaZ/fillhisto_sswwAnalysis1001_%d_27.root",year),"sswwbvbssel_detajj", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#Delta#phi_{jj}","",Form("anaZ/fillhisto_sswwAnalysis1001_%d_28.root",year),"sswwvbssel_dphijj", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#Delta#phi_{jj}","",Form("anaZ/fillhisto_sswwAnalysis1001_%d_29.root",year),"sswwbvbssel_dphijj", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"Zep(V)","",Form("anaZ/fillhisto_sswwAnalysis1001_%d_30.root",year),"sswwvbssel_zepvv", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"Zep(V)","",Form("anaZ/fillhisto_sswwAnalysis1001_%d_31.root",year),"sswwbvbssel_zepvv", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"BDT","",Form("anaZ/fillhisto_sswwAnalysis1001_%d_32.root",year),"sswwvbssel_bdt_vbfincl", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"BDT","",Form("anaZ/fillhisto_sswwAnalysis1001_%d_33.root",year),"sswwbvbssel_bdt_vbfincl", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
  }
  else if(nsel == "zmet"){
    legendBSM="";
    isNeverBlinded=0;
    isBlinded=0;
    fidAnaName="";
    mlfitResult="";
    channelName="XXX"; 
    SF_DY=1;
    finalPlot(0,1,"m_{ll}","GeV",Form("anaZ/fillhisto_zmetAnalysis1001_%d_0.root",year), "zmetmmsel_mll", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{ll}","GeV",Form("anaZ/fillhisto_zmetAnalysis1001_%d_1.root",year), "zmetemsel_mll", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{ll}","GeV",Form("anaZ/fillhisto_zmetAnalysis1001_%d_2.root",year), "zmeteesel_mll", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p^{ll}_{T}","GeV",Form("anaZ/fillhisto_zmetAnalysis1001_%d_3.root",year), "zmetmmsel_ptll", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p^{ll}_{T}","GeV",Form("anaZ/fillhisto_zmetAnalysis1001_%d_4.root",year), "zmetemsel_ptll", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p^{ll}_{T}","GeV",Form("anaZ/fillhisto_zmetAnalysis1001_%d_5.root",year), "zmeteesel_ptll", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#DeltaR_{ll}","",Form("anaZ/fillhisto_zmetAnalysis1001_%d_6.root",year), "zmetmmsel_drll", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#DeltaR_{ll}","",Form("anaZ/fillhisto_zmetAnalysis1001_%d_7.root",year), "zmetemsel_drll", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#DeltaR_{ll}","",Form("anaZ/fillhisto_zmetAnalysis1001_%d_8.root",year), "zmeteesel_drll", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#Delta#phi_{ll}","",Form("anaZ/fillhisto_zmetAnalysis1001_%d_9.root",year),"zmetmmsel_dphill", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#Delta#phi_{ll}","",Form("anaZ/fillhisto_zmetAnalysis1001_%d_10.root",year),"zmetemsel_dphill", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#Delta#phi_{ll}","",Form("anaZ/fillhisto_zmetAnalysis1001_%d_11.root",year),"zmeteesel_dphill", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{l1}","GeV",Form("anaZ/fillhisto_zmetAnalysis1001_%d_12.root",year),"zmetmmsel_ptl1", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{l1}","GeV",Form("anaZ/fillhisto_zmetAnalysis1001_%d_13.root",year),"zmetemsel_ptl1", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{l1}","GeV",Form("anaZ/fillhisto_zmetAnalysis1001_%d_14.root",year),"zmeteesel_ptl1", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{l2}","GeV",Form("anaZ/fillhisto_zmetAnalysis1001_%d_15.root",year),"zmetmmsel_ptl2", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{l2}","GeV",Form("anaZ/fillhisto_zmetAnalysis1001_%d_16.root",year),"zmetemsel_ptl2", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{l2}","GeV",Form("anaZ/fillhisto_zmetAnalysis1001_%d_17.root",year),"zmeteesel_ptl2", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#eta^{l1}","",Form("anaZ/fillhisto_zmetAnalysis1001_%d_18.root",year),"zmetmmsel_etal1", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#eta^{l1}","",Form("anaZ/fillhisto_zmetAnalysis1001_%d_19.root",year),"zmetemsel_etal1", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#eta^{l1}","",Form("anaZ/fillhisto_zmetAnalysis1001_%d_20.root",year),"zmeteesel_etal1", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#eta^{l2}","",Form("anaZ/fillhisto_zmetAnalysis1001_%d_21.root",year),"zmetmmsel_etal2", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#eta^{l2}","",Form("anaZ/fillhisto_zmetAnalysis1001_%d_22.root",year),"zmetemsel_etal2", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#eta^{l2}","",Form("anaZ/fillhisto_zmetAnalysis1001_%d_23.root",year),"zmeteesel_etal2", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"n_{jets}","",Form("anaZ/fillhisto_zmetAnalysis1001_%d_24.root",year),"zmetmmsel_njets", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"n_{jets}","",Form("anaZ/fillhisto_zmetAnalysis1001_%d_25.root",year),"zmetemsel_njets", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"n_{jets}","",Form("anaZ/fillhisto_zmetAnalysis1001_%d_26.root",year),"zmeteesel_njets", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{miss}","GeV",Form("anaZ/fillhisto_zmetAnalysis1001_%d_27.root",year),"zmetmmsel_ptmiss", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{miss}","GeV",Form("anaZ/fillhisto_zmetAnalysis1001_%d_28.root",year),"zmetemsel_ptmiss", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{miss}","GeV",Form("anaZ/fillhisto_zmetAnalysis1001_%d_29.root",year),"zmeteesel_ptmiss", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"|p^{ll}_{T}-p_{T}^{miss}|/p^{ll}_{T}","",Form("anaZ/fillhisto_zmetAnalysis1001_%d_30.root",year),"zmetmmsel_ptbalance", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"|p^{ll}_{T}-p_{T}^{miss}|/p^{ll}_{T}","",Form("anaZ/fillhisto_zmetAnalysis1001_%d_31.root",year),"zmetemsel_ptbalance", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"|p^{ll}_{T}-p_{T}^{miss}|/p^{ll}_{T}","",Form("anaZ/fillhisto_zmetAnalysis1001_%d_32.root",year),"zmeteesel_ptbalance", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"|p^{llj}_{T}-p_{T}^{miss}|/p^{llj}_{T}","",Form("anaZ/fillhisto_zmetAnalysis1001_%d_33.root",year),"zmetmmsel_ptjbalance", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"|p^{llj}_{T}-p_{T}^{miss}|/p^{llj}_{T}","",Form("anaZ/fillhisto_zmetAnalysis1001_%d_34.root",year),"zmetemsel_ptjbalance", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"|p^{llj}_{T}-p_{T}^{miss}|/p^{llj}_{T}","",Form("anaZ/fillhisto_zmetAnalysis1001_%d_35.root",year),"zmeteesel_ptjbalance", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#Delta#phi_{ll,p_{T}^{miss}}","",Form("anaZ/fillhisto_zmetAnalysis1001_%d_36.root",year),"zmetmmsel_dphillmet", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#Delta#phi_{ll,p_{T}^{miss}}","",Form("anaZ/fillhisto_zmetAnalysis1001_%d_37.root",year),"zmetemsel_dphillmet", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#Delta#phi_{ll,p_{T}^{miss}}","",Form("anaZ/fillhisto_zmetAnalysis1001_%d_38.root",year),"zmeteesel_dphillmet", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#Delta#phi_{llj,p_{T}^{miss}}","",Form("anaZ/fillhisto_zmetAnalysis1001_%d_39.root",year),"zmetmmsel_dphilljmet", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#Delta#phi_{llj,p_{T}^{miss}}","",Form("anaZ/fillhisto_zmetAnalysis1001_%d_40.root",year),"zmetemsel_dphilljmet", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#Delta#phi_{llj,p_{T}^{miss}}","",Form("anaZ/fillhisto_zmetAnalysis1001_%d_41.root",year),"zmeteesel_dphilljmet", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#Delta#phi_{j,p_{T}^{miss}}","",Form("anaZ/fillhisto_zmetAnalysis1001_%d_42.root",year),"zmetmmsel_dphijmet", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#Delta#phi_{j,p_{T}^{miss}}","",Form("anaZ/fillhisto_zmetAnalysis1001_%d_43.root",year),"zmetemsel_dphijmet", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#Delta#phi_{j,p_{T}^{miss}}","",Form("anaZ/fillhisto_zmetAnalysis1001_%d_44.root",year),"zmeteesel_dphijmet", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{T}","GeV",Form("anaZ/fillhisto_zmetAnalysis1001_%d_45.root",year),"zmetmmsel_mt", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{T}","GeV",Form("anaZ/fillhisto_zmetAnalysis1001_%d_46.root",year),"zmetemsel_mt", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{T}","GeV",Form("anaZ/fillhisto_zmetAnalysis1001_%d_47.root",year),"zmeteesel_mt", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p^{ll}_{T}","GeV",Form("anaZ/fillhisto_zmetAnalysis1001_%d_48.root",year), "zmetbmmsel_ptll", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p^{ll}_{T}","GeV",Form("anaZ/fillhisto_zmetAnalysis1001_%d_49.root",year), "zmetbemsel_ptll", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p^{ll}_{T}","GeV",Form("anaZ/fillhisto_zmetAnalysis1001_%d_50.root",year), "zmetbeesel_ptll", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{T}","GeV",Form("anaZ/fillhisto_zmetAnalysis1001_%d_51.root",year),"zmetbmmsel_mt", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{T}","GeV",Form("anaZ/fillhisto_zmetAnalysis1001_%d_52.root",year),"zmetbemsel_mt", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{T}","GeV",Form("anaZ/fillhisto_zmetAnalysis1001_%d_53.root",year),"zmetbeesel_mt", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{miss}","GeV",Form("anaZ/fillhisto_zmetAnalysis1001_%d_54.root",year),"zmetbmmsel_met", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{miss}","GeV",Form("anaZ/fillhisto_zmetAnalysis1001_%d_55.root",year),"zmetbemsel_met", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{miss}","GeV",Form("anaZ/fillhisto_zmetAnalysis1001_%d_56.root",year),"zmetbeesel_met", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"|p^{llg}_{T}-p_{T}^{miss}|/p^{llg}_{T}","",Form("anaZ/fillhisto_zmetAnalysis1001_%d_57.root",year),"zmetgmmsel_ptgbalance", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"|p^{llg}_{T}-p_{T}^{miss}|/p^{llg}_{T}","",Form("anaZ/fillhisto_zmetAnalysis1001_%d_58.root",year),"zmetgemsel_ptgbalance", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"|p^{llg}_{T}-p_{T}^{miss}|/p^{llg}_{T}","",Form("anaZ/fillhisto_zmetAnalysis1001_%d_59.root",year),"zmetgeesel_ptgbalance", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"|p^{llgj}_{T}-p_{T}^{miss}|/p^{llgj}_{T}","",Form("anaZ/fillhisto_zmetAnalysis1001_%d_60.root",year),"zmetgmmsel_ptgjbalance", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"|p^{llgj}_{T}-p_{T}^{miss}|/p^{llgj}_{T}","",Form("anaZ/fillhisto_zmetAnalysis1001_%d_61.root",year),"zmetgemsel_ptgjbalance", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"|p^{llgj}_{T}-p_{T}^{miss}|/p^{llgj}_{T}","",Form("anaZ/fillhisto_zmetAnalysis1001_%d_62.root",year),"zmetgeesel_ptgjbalance", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#Delta#phi_{llg,p_{T}^{miss}}","",Form("anaZ/fillhisto_zmetAnalysis1001_%d_63.root",year),"zmetgmmsel_dphillgmet", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#Delta#phi_{llg,p_{T}^{miss}}","",Form("anaZ/fillhisto_zmetAnalysis1001_%d_64.root",year),"zmetgemsel_dphillgmet", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#Delta#phi_{llg,p_{T}^{miss}}","",Form("anaZ/fillhisto_zmetAnalysis1001_%d_65.root",year),"zmetgeesel_dphillgmet", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#Delta#phi_{llgj,p_{T}^{miss}}","",Form("anaZ/fillhisto_zmetAnalysis1001_%d_66.root",year),"zmetgmmsel_dphillgjmet", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#Delta#phi_{llgj,p_{T}^{miss}}","",Form("anaZ/fillhisto_zmetAnalysis1001_%d_67.root",year),"zmetgemsel_dphillgjmet", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"#Delta#phi_{llgj,p_{T}^{miss}}","",Form("anaZ/fillhisto_zmetAnalysis1001_%d_68.root",year),"zmetgeesel_dphillgjmet", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{miss}","GeV",Form("anaZ/fillhisto_zmetAnalysis1001_%d_69.root",year),"zmetgmmsel_met", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{miss}","GeV",Form("anaZ/fillhisto_zmetAnalysis1001_%d_70.root",year),"zmetgemsel_met", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{miss}","GeV",Form("anaZ/fillhisto_zmetAnalysis1001_%d_71.root",year),"zmetgeesel_met", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{T}","GeV",Form("anaZ/fillhisto_zmetAnalysis1001_%d_72.root",year),"zmetgmmsel_mtg", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{T}","GeV",Form("anaZ/fillhisto_zmetAnalysis1001_%d_73.root",year),"zmetgemsel_mtg", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"m_{T}","GeV",Form("anaZ/fillhisto_zmetAnalysis1001_%d_74.root",year),"zmetgeesel_mtg", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"N_{jets}","",Form("anaZ/fillhisto_zmetAnalysis1001_%d_75.root",year),"zmetgmmsel_njets", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"N_{jets}","",Form("anaZ/fillhisto_zmetAnalysis1001_%d_76.root",year),"zmetgemsel_njets", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"N_{jets}","",Form("anaZ/fillhisto_zmetAnalysis1001_%d_77.root",year),"zmetgeesel_njets", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{miss} significance","",Form("anaZ/fillhisto_zmetAnalysis1001_%d_78.root",year),"zmetgmmsel_metsig", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{miss} significance","",Form("anaZ/fillhisto_zmetAnalysis1001_%d_79.root",year),"zmetgemsel_metsig", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{miss} significance","",Form("anaZ/fillhisto_zmetAnalysis1001_%d_80.root",year),"zmetgeesel_metsig", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"jetPtgFrac","",Form("anaZ/fillhisto_zmetAnalysis1001_%d_81.root",year),"zmetgmmsel_jetptfrac", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"jetPtgFrac","",Form("anaZ/fillhisto_zmetAnalysis1001_%d_82.root",year),"zmetgemsel_jetptfrac", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"jetPtgFrac","",Form("anaZ/fillhisto_zmetAnalysis1001_%d_83.root",year),"zmetgeesel_jetptfrac", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{miss} significance","",Form("anaZ/fillhisto_zmetAnalysis1001_%d_84.root",year),"zmetmmsel_metsig", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{miss} significance","",Form("anaZ/fillhisto_zmetAnalysis1001_%d_85.root",year),"zmetemsel_metsig", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"p_{T}^{miss} significance","",Form("anaZ/fillhisto_zmetAnalysis1001_%d_86.root",year),"zmeteesel_metsig", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"jetPtFrac","",Form("anaZ/fillhisto_zmetAnalysis1001_%d_87.root",year),"zmetmmsel_jetptfrac", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"jetPtFrac","",Form("anaZ/fillhisto_zmetAnalysis1001_%d_88.root",year),"zmetemsel_jetptfrac", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
    finalPlot(0,1,"jetPtFrac","",Form("anaZ/fillhisto_zmetAnalysis1001_%d_89.root",year),"zmeteesel_jetptfrac", 0,year,legendBSM.Data(),SF_DY,isBlinded,"",1,applyScaling,mlfitResult.Data(),channelName.Data());
  }
  else if(nsel == "gj"){
    legendBSM="";
    isNeverBlinded=0;
    isBlinded=0;
    fidAnaName="";
    channelName="XXX"; 
    finalPlot(0,1,"#sigma_{i#eta i#eta}","",Form("anaZ/fillhisto_gammaAnalysis1001_%d_3.root",year),"sietaieta_pt0_eta0_obs", 1,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,"gammajet/result0_20bins/fitDiagnosticsgj_pt0_eta0_obs.root",channelName.Data(),1);
    finalPlot(0,1,"#sigma_{i#eta i#eta}","",Form("anaZ/fillhisto_gammaAnalysis1001_%d_13.root",year),"sietaieta_pt1_eta0_obs", 1,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,"gammajet/result0_20bins/fitDiagnosticsgj_pt1_eta0_obs.root",channelName.Data(),1);
    finalPlot(0,1,"#sigma_{i#eta i#eta}","",Form("anaZ/fillhisto_gammaAnalysis1001_%d_23.root",year),"sietaieta_pt2_eta0_obs", 1,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,"gammajet/result0_20bins/fitDiagnosticsgj_pt2_eta0_obs.root",channelName.Data(),1);
    finalPlot(0,1,"#sigma_{i#eta i#eta}","",Form("anaZ/fillhisto_gammaAnalysis1001_%d_33.root",year),"sietaieta_pt3_eta0_obs", 1,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,"gammajet/result0_20bins/fitDiagnosticsgj_pt3_eta0_obs.root",channelName.Data(),1);
    finalPlot(0,1,"#sigma_{i#eta i#eta}","",Form("anaZ/fillhisto_gammaAnalysis1001_%d_43.root",year),"sietaieta_pt4_eta0_obs", 1,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,"gammajet/result0_20bins/fitDiagnosticsgj_pt4_eta0_obs.root",channelName.Data(),1);
    finalPlot(0,1,"#sigma_{i#eta i#eta}","",Form("anaZ/fillhisto_gammaAnalysis1001_%d_53.root",year),"sietaieta_pt5_eta0_obs", 1,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,"gammajet/result0_20bins/fitDiagnosticsgj_pt5_eta0_obs.root",channelName.Data(),1);
    finalPlot(0,1,"#sigma_{i#eta i#eta}","",Form("anaZ/fillhisto_gammaAnalysis1001_%d_63.root",year),"sietaieta_pt6_eta0_obs", 1,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,"gammajet/result0_20bins/fitDiagnosticsgj_pt6_eta0_obs.root",channelName.Data(),1);
    finalPlot(0,1,"#sigma_{i#eta i#eta}","",Form("anaZ/fillhisto_gammaAnalysis1001_%d_73.root",year),"sietaieta_pt7_eta0_obs", 1,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,"gammajet/result0_20bins/fitDiagnosticsgj_pt7_eta0_obs.root",channelName.Data(),1);
    finalPlot(0,1,"#sigma_{i#eta i#eta}","",Form("anaZ/fillhisto_gammaAnalysis1001_%d_83.root",year),"sietaieta_pt8_eta0_obs", 1,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,"gammajet/result0_20bins/fitDiagnosticsgj_pt8_eta0_obs.root",channelName.Data(),1);
    finalPlot(0,1,"#sigma_{i#eta i#eta}","",Form("anaZ/fillhisto_gammaAnalysis1001_%d_93.root",year),"sietaieta_pt9_eta0_obs", 1,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,"gammajet/result0_20bins/fitDiagnosticsgj_pt9_eta0_obs.root",channelName.Data(),1);
    finalPlot(0,1,"#sigma_{i#eta i#eta}","",Form("anaZ/fillhisto_gammaAnalysis1001_%d_103.root",year),"sietaieta_pt10_eta0_obs",1,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,"gammajet/result0_20bins/fitDiagnosticsgj_pt10_eta0_obs.root",channelName.Data(),1);
    finalPlot(0,1,"#sigma_{i#eta i#eta}","",Form("anaZ/fillhisto_gammaAnalysis1001_%d_113.root",year),"sietaieta_pt11_eta0_obs",1,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,"gammajet/result0_20bins/fitDiagnosticsgj_pt11_eta0_obs.root",channelName.Data(),1);
    finalPlot(0,1,"#sigma_{i#eta i#eta}","",Form("anaZ/fillhisto_gammaAnalysis1001_%d_123.root",year),"sietaieta_pt12_eta0_obs",1,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,"gammajet/result0_20bins/fitDiagnosticsgj_pt12_eta0_obs.root",channelName.Data(),1);
    finalPlot(0,1,"#sigma_{i#eta i#eta}","",Form("anaZ/fillhisto_gammaAnalysis1001_%d_133.root",year),"sietaieta_pt13_eta0_obs",1,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,"gammajet/result0_20bins/fitDiagnosticsgj_pt13_eta0_obs.root",channelName.Data(),1);
    finalPlot(0,1,"#sigma_{i#eta i#eta}","",Form("anaZ/fillhisto_gammaAnalysis1001_%d_143.root",year),"sietaieta_pt14_eta0_obs",1,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,"gammajet/result0_20bins/fitDiagnosticsgj_pt14_eta0_obs.root",channelName.Data(),1);
    finalPlot(0,1,"#sigma_{i#eta i#eta}","",Form("anaZ/fillhisto_gammaAnalysis1001_%d_153.root",year),"sietaieta_pt15_eta0_obs",1,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,"gammajet/result0_20bins/fitDiagnosticsgj_pt15_eta0_obs.root",channelName.Data(),1);
    finalPlot(0,1,"#sigma_{i#eta i#eta}","",Form("anaZ/fillhisto_gammaAnalysis1001_%d_163.root",year),"sietaieta_pt16_eta0_obs",1,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,"gammajet/result0_20bins/fitDiagnosticsgj_pt16_eta0_obs.root",channelName.Data(),1);
    finalPlot(0,1,"#sigma_{i#eta i#eta}","",Form("anaZ/fillhisto_gammaAnalysis1001_%d_173.root",year),"sietaieta_pt17_eta0_obs",1,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,"gammajet/result0_20bins/fitDiagnosticsgj_pt17_eta0_obs.root",channelName.Data(),1);
    finalPlot(0,1,"#sigma_{i#eta i#eta}","",Form("anaZ/fillhisto_gammaAnalysis1001_%d_183.root",year),"sietaieta_pt18_eta0_obs",1,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,"gammajet/result0_20bins/fitDiagnosticsgj_pt18_eta0_obs.root",channelName.Data(),1);
    finalPlot(0,1,"#sigma_{i#eta i#eta}","",Form("anaZ/fillhisto_gammaAnalysis1001_%d_193.root",year),"sietaieta_pt19_eta0_obs",1,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,"gammajet/result0_20bins/fitDiagnosticsgj_pt19_eta0_obs.root",channelName.Data(),1);

    finalPlot(0,1,"#sigma_{i#eta i#eta}","",Form("anaZ/fillhisto_gammaAnalysis1001_%d_7.root",year),"sietaieta_pt0_eta1_obs", 1,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,"gammajet/result0_20bins/fitDiagnosticsgj_pt0_eta1_obs.root",channelName.Data(),1);
    finalPlot(0,1,"#sigma_{i#eta i#eta}","",Form("anaZ/fillhisto_gammaAnalysis1001_%d_17.root",year),"sietaieta_pt1_eta1_obs", 1,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,"gammajet/result0_20bins/fitDiagnosticsgj_pt1_eta1_obs.root",channelName.Data(),1);
    finalPlot(0,1,"#sigma_{i#eta i#eta}","",Form("anaZ/fillhisto_gammaAnalysis1001_%d_27.root",year),"sietaieta_pt2_eta1_obs", 1,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,"gammajet/result0_20bins/fitDiagnosticsgj_pt2_eta1_obs.root",channelName.Data(),1);
    finalPlot(0,1,"#sigma_{i#eta i#eta}","",Form("anaZ/fillhisto_gammaAnalysis1001_%d_37.root",year),"sietaieta_pt3_eta1_obs", 1,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,"gammajet/result0_20bins/fitDiagnosticsgj_pt3_eta1_obs.root",channelName.Data(),1);
    finalPlot(0,1,"#sigma_{i#eta i#eta}","",Form("anaZ/fillhisto_gammaAnalysis1001_%d_47.root",year),"sietaieta_pt4_eta1_obs", 1,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,"gammajet/result0_20bins/fitDiagnosticsgj_pt4_eta1_obs.root",channelName.Data(),1);
    finalPlot(0,1,"#sigma_{i#eta i#eta}","",Form("anaZ/fillhisto_gammaAnalysis1001_%d_57.root",year),"sietaieta_pt5_eta1_obs", 1,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,"gammajet/result0_20bins/fitDiagnosticsgj_pt5_eta1_obs.root",channelName.Data(),1);
    finalPlot(0,1,"#sigma_{i#eta i#eta}","",Form("anaZ/fillhisto_gammaAnalysis1001_%d_67.root",year),"sietaieta_pt6_eta1_obs", 1,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,"gammajet/result0_20bins/fitDiagnosticsgj_pt6_eta1_obs.root",channelName.Data(),1);
    finalPlot(0,1,"#sigma_{i#eta i#eta}","",Form("anaZ/fillhisto_gammaAnalysis1001_%d_77.root",year),"sietaieta_pt7_eta1_obs", 1,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,"gammajet/result0_20bins/fitDiagnosticsgj_pt7_eta1_obs.root",channelName.Data(),1);
    finalPlot(0,1,"#sigma_{i#eta i#eta}","",Form("anaZ/fillhisto_gammaAnalysis1001_%d_87.root",year),"sietaieta_pt8_eta1_obs", 1,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,"gammajet/result0_20bins/fitDiagnosticsgj_pt8_eta1_obs.root",channelName.Data(),1);
    finalPlot(0,1,"#sigma_{i#eta i#eta}","",Form("anaZ/fillhisto_gammaAnalysis1001_%d_97.root",year),"sietaieta_pt9_eta1_obs", 1,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,"gammajet/result0_20bins/fitDiagnosticsgj_pt9_eta1_obs.root",channelName.Data(),1);
    finalPlot(0,1,"#sigma_{i#eta i#eta}","",Form("anaZ/fillhisto_gammaAnalysis1001_%d_107.root",year),"sietaieta_pt10_eta1_obs",1,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,"gammajet/result0_20bins/fitDiagnosticsgj_pt10_eta1_obs.root",channelName.Data(),1);
    finalPlot(0,1,"#sigma_{i#eta i#eta}","",Form("anaZ/fillhisto_gammaAnalysis1001_%d_117.root",year),"sietaieta_pt11_eta1_obs",1,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,"gammajet/result0_20bins/fitDiagnosticsgj_pt11_eta1_obs.root",channelName.Data(),1);
    finalPlot(0,1,"#sigma_{i#eta i#eta}","",Form("anaZ/fillhisto_gammaAnalysis1001_%d_127.root",year),"sietaieta_pt12_eta1_obs",1,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,"gammajet/result0_20bins/fitDiagnosticsgj_pt12_eta1_obs.root",channelName.Data(),1);
    finalPlot(0,1,"#sigma_{i#eta i#eta}","",Form("anaZ/fillhisto_gammaAnalysis1001_%d_137.root",year),"sietaieta_pt13_eta1_obs",1,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,"gammajet/result0_20bins/fitDiagnosticsgj_pt13_eta1_obs.root",channelName.Data(),1);
    finalPlot(0,1,"#sigma_{i#eta i#eta}","",Form("anaZ/fillhisto_gammaAnalysis1001_%d_147.root",year),"sietaieta_pt14_eta1_obs",1,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,"gammajet/result0_20bins/fitDiagnosticsgj_pt14_eta1_obs.root",channelName.Data(),1);
    finalPlot(0,1,"#sigma_{i#eta i#eta}","",Form("anaZ/fillhisto_gammaAnalysis1001_%d_157.root",year),"sietaieta_pt15_eta1_obs",1,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,"gammajet/result0_20bins/fitDiagnosticsgj_pt15_eta1_obs.root",channelName.Data(),1);
    finalPlot(0,1,"#sigma_{i#eta i#eta}","",Form("anaZ/fillhisto_gammaAnalysis1001_%d_167.root",year),"sietaieta_pt16_eta1_obs",1,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,"gammajet/result0_20bins/fitDiagnosticsgj_pt16_eta1_obs.root",channelName.Data(),1);
    finalPlot(0,1,"#sigma_{i#eta i#eta}","",Form("anaZ/fillhisto_gammaAnalysis1001_%d_177.root",year),"sietaieta_pt17_eta1_obs",1,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,"gammajet/result0_20bins/fitDiagnosticsgj_pt17_eta1_obs.root",channelName.Data(),1);
    finalPlot(0,1,"#sigma_{i#eta i#eta}","",Form("anaZ/fillhisto_gammaAnalysis1001_%d_187.root",year),"sietaieta_pt18_eta1_obs",1,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,"gammajet/result0_20bins/fitDiagnosticsgj_pt18_eta1_obs.root",channelName.Data(),1);
    finalPlot(0,1,"#sigma_{i#eta i#eta}","",Form("anaZ/fillhisto_gammaAnalysis1001_%d_197.root",year),"sietaieta_pt19_eta1_obs",1,year,legendBSM.Data(),1.0,isBlinded,"",1,applyScaling,"gammajet/result0_20bins/fitDiagnosticsgj_pt19_eta1_obs.root",channelName.Data(),1);
  }
}
