import ROOT
import correctionlib

correctionlib.register_pyroot_binding()
ROOT.gInterpreter.Declare('#include "mysf.h"')
ROOT.gInterpreter.Load("mysf.so")
ROOT.gInterpreter.ProcessLine('auto corr = MyCorrections(2022);')
ROOT.gInterpreter.ProcessLine('corr.eval_electronSF((char*)"2018", (char*)"sf", (char*)"Medium", 1.1, 34.0)')
ROOT.gInterpreter.ProcessLine('corr.eval_electronSF((char*)"2018", (char*)"sf", (char*)"RecoAbove20", 1.1, 20.0)')
ROOT.gInterpreter.ProcessLine('corr.eval_electronSF((char*)"2018", (char*)"sf", (char*)"RecoBelow20", 1.1, 19.999)')
ROOT.gInterpreter.ProcessLine('corr.eval_muonIDSF((char*)"2018_UL",(char*)"sf",(char*)"Medium", (double)1.1, 25.0)')
ROOT.gInterpreter.ProcessLine('corr.eval_btvSF((char*)"central",(char*)"T",1.1,35.0,4)')
ROOT.gInterpreter.ProcessLine('corr.eval_btvSF((char*)"central",(char*)"T",1.1,35.0,5)')
ROOT.gInterpreter.ProcessLine('corr.eval_btvSF((char*)"central",(char*)"T",1.1,35.0,0)')
ROOT.gInterpreter.ProcessLine('corr.eval_puJetIDSF((char*)"nom",(char*)"L",4.7,20.0)')
ROOT.gInterpreter.ProcessLine('corr.eval_tauJETSF(38.2,11,5,"Tight","nom")')
ROOT.gInterpreter.ProcessLine('corr.eval_tauELESF(0.3,3,"Tight","nom")')
ROOT.gInterpreter.ProcessLine('corr.eval_tauMUOSF(-2.1,5,"Tight","nom")')
print("eval_jetCORR")
ROOT.gInterpreter.ProcessLine('corr.eval_jetCORR(0.5,1.,150,15,-1)')
ROOT.gInterpreter.ProcessLine('corr.eval_jetCORR(0.5,1.,150,15,1)')
ROOT.gInterpreter.ProcessLine('corr.eval_jetCORR(0.5,1.,150,15,6)')
ROOT.gInterpreter.ProcessLine('corr.eval_jesUnc(1.5,30,0)')
ROOT.gInterpreter.ProcessLine('corr.eval_jerMethod1(1.5,30, 0)')
ROOT.gInterpreter.ProcessLine('corr.eval_jerMethod1(1.5,30,+1)')
ROOT.gInterpreter.ProcessLine('corr.eval_jerMethod1(1.5,30,-1)')
ROOT.gInterpreter.ProcessLine('corr.eval_jerMethod2(2.5,15.9,21)')
ROOT.gInterpreter.ProcessLine('corr.eval_jetVetoMap(2.5,-2.2,0)')
ROOT.gInterpreter.ProcessLine('corr.eval_jetVetoMap(6.5,-2.2,0)')
ROOT.gInterpreter.ProcessLine('corr.eval_jetVetoMap(2.5,-6.2,0)')
