import ROOT
import correctionlib

correctionlib.register_pyroot_binding()
ROOT.gInterpreter.Declare('#include "mysf.h"')
print("eval_20221")
ROOT.gInterpreter.ProcessLine('auto corr = MyCorrections(20221);')
ROOT.gInterpreter.ProcessLine('corr.eval_electronSF((char*)"2022FG", (char*)"sf", (char*)"wp80iso", 1.1, 34.0)')
ROOT.gInterpreter.ProcessLine('corr.eval_electronSF((char*)"2022FG", (char*)"sfup", (char*)"wp80iso", 1.1, 34.0)')
ROOT.gInterpreter.ProcessLine('corr.eval_electronSF((char*)"2022FG", (char*)"sfdown", (char*)"Medium", 1.1, 34.0)')
ROOT.gInterpreter.ProcessLine('corr.eval_electronSF((char*)"2022FG", (char*)"sf", (char*)"RecoBelow20", 1.1, 19.999)')
ROOT.gInterpreter.ProcessLine('corr.eval_electronSF((char*)"2022FG", (char*)"sf", (char*)"Reco20to75", 1.1, 20.0)')
ROOT.gInterpreter.ProcessLine('corr.eval_electronSF((char*)"2022FG", (char*)"sf", (char*)"RecoAbove75", 1.1, 75.0)')
ROOT.gInterpreter.ProcessLine('corr.eval_photonSF((char*)"2022FG", (char*)"sf", (char*)"Medium", 1.1, 30.0)')
print("eval_el_scale_smeaer")
ROOT.gInterpreter.ProcessLine('corr.eval_electronScale((char*)"total_correction", 1, 361000, 0.5, 0.99, 40)')
ROOT.gInterpreter.ProcessLine('corr.eval_electronScale((char*)"total_uncertainty", 1, 361000, 0.5, 0.99, 40)')
ROOT.gInterpreter.ProcessLine('corr.eval_electronScale((char*)"total_uncertainty", 1, 1, 0.5, 0.99, 40)')
ROOT.gInterpreter.ProcessLine('corr.eval_electronSmearing((char*)"rho", 0.5, 0.99)')
ROOT.gInterpreter.ProcessLine('corr.eval_electronSmearing((char*)"err_rho", 0.5, 0.99)')
print("eval_muon_med")
ROOT.gInterpreter.ProcessLine('corr.eval_muonTRKSF((double)0.9, 35, 35,(char*)"nominal")')
ROOT.gInterpreter.ProcessLine('corr.eval_muonIDSF ((double)0.9, 35,    (char*)"nominal")')
ROOT.gInterpreter.ProcessLine('corr.eval_muonISOSF((double)0.9, 35,    (char*)"nominal")')
ROOT.gInterpreter.ProcessLine('corr.eval_muonTRKSF((double)0.9, 35, 35,(char*)"syst")')
ROOT.gInterpreter.ProcessLine('corr.eval_muonIDSF ((double)0.9, 35,    (char*)"syst")')
ROOT.gInterpreter.ProcessLine('corr.eval_muonISOSF((double)0.9, 35,    (char*)"syst")')
ROOT.gInterpreter.ProcessLine('corr.eval_muonTRKSF((double)0.9, 35, 35,(char*)"stat")')
ROOT.gInterpreter.ProcessLine('corr.eval_muonIDSF ((double)0.9, 35,    (char*)"stat")')
ROOT.gInterpreter.ProcessLine('corr.eval_muonISOSF((double)0.9, 35,    (char*)"stat")')
print("eval_muon_high")
ROOT.gInterpreter.ProcessLine('corr.eval_muonTRKSF((double)0.9, 350, 350,(char*)"nominal")')
ROOT.gInterpreter.ProcessLine('corr.eval_muonIDSF ((double)0.9, 350,     (char*)"nominal")')
ROOT.gInterpreter.ProcessLine('corr.eval_muonISOSF((double)0.9, 350,     (char*)"nominal")')
ROOT.gInterpreter.ProcessLine('corr.eval_muonTRKSF((double)0.9, 350, 350,(char*)"syst")')
ROOT.gInterpreter.ProcessLine('corr.eval_muonIDSF ((double)0.9, 350,     (char*)"syst")')
ROOT.gInterpreter.ProcessLine('corr.eval_muonISOSF((double)0.9, 350,     (char*)"syst")')
ROOT.gInterpreter.ProcessLine('corr.eval_muonTRKSF((double)0.9, 350, 350,(char*)"stat")')
ROOT.gInterpreter.ProcessLine('corr.eval_muonIDSF ((double)0.9, 350,     (char*)"stat")')
ROOT.gInterpreter.ProcessLine('corr.eval_muonISOSF((double)0.9, 350,     (char*)"stat")')
print("eval_btv")
ROOT.gInterpreter.ProcessLine('corr.eval_btvSF((char*)"central",(char*)"T",1.1,35.0,4)')
ROOT.gInterpreter.ProcessLine('corr.eval_btvSF((char*)"central",(char*)"T",1.1,35.0,5)')
ROOT.gInterpreter.ProcessLine('corr.eval_btvSF((char*)"central",(char*)"T",1.1,35.0,0)')
#ROOT.gInterpreter.ProcessLine('corr.eval_puJetIDSF((char*)"nom",(char*)"L",4.7,20.0)')
ROOT.gInterpreter.ProcessLine('corr.eval_tauJETSF(65.2,11,5,"Tight","Tight","default")')
print("eval_jetCORR")
ROOT.gInterpreter.ProcessLine('corr.eval_jesUnc(1.5,30,0)')
ROOT.gInterpreter.ProcessLine('corr.eval_jesUnc(1.5,30,1)')
ROOT.gInterpreter.ProcessLine('corr.eval_jesUnc(1.5,30,2)')
ROOT.gInterpreter.ProcessLine('corr.eval_jesUnc(1.5,30,3)')
ROOT.gInterpreter.ProcessLine('corr.eval_jesUnc(1.5,30,4)')
ROOT.gInterpreter.ProcessLine('corr.eval_jesUnc(1.5,30,5)')
ROOT.gInterpreter.ProcessLine('corr.eval_jesUnc(1.5,30,6)')
print("eval_jetCORR_others")
ROOT.gInterpreter.ProcessLine('corr.eval_jetCORR(0.5,1.,150,15,-1)')
ROOT.gInterpreter.ProcessLine('corr.eval_jetCORR(0.5,1.,150,15,1)')
ROOT.gInterpreter.ProcessLine('corr.eval_jerMethod1(1.5,30, 0)')
ROOT.gInterpreter.ProcessLine('corr.eval_jerMethod1(1.5,30,+1)')
ROOT.gInterpreter.ProcessLine('corr.eval_jerMethod1(1.5,30,-1)')
ROOT.gInterpreter.ProcessLine('corr.eval_jerMethod2(2.5,15.9,21)')
ROOT.gInterpreter.ProcessLine('corr.eval_jetVetoMap(2.5,-2.2,0)')
ROOT.gInterpreter.ProcessLine('corr.eval_jetVetoMap(6.5,-2.2,0)')
ROOT.gInterpreter.ProcessLine('corr.eval_jetVetoMap(2.5,-6.2,0)')
